# Exercício Prático — Análise de Qualidade do Ar no Brasil com Python

## Contexto do Problema

A poluição do ar é um problema crescente em diversas cidades brasileiras. O Ministério do Meio Ambiente
deseja analisar dados coletados por sensores ambientais instalados em diferentes capitais para entender:

- quais cidades apresentam maior concentração de poluentes
- quais períodos do ano apresentam pior qualidade do ar
- quais poluentes são mais críticos

## Objetivos da atividade

O aluno deverá aprender a:

- carregar dados ambientais com Pandas
- realizar inspeção inicial do dataset
- aplicar filtros por cidade e nível de alerta
- calcular médias e rankings de poluentes
- identificar padrões temporais
- interpretar dados ambientais

# Parte 1 - Preparação do ambiente

In [14]:
import pandas as pd
DATA_PATH = "qualidade_ar_brasil.csv"

df = pd.read_csv(DATA_PATH)

In [16]:
df.shape

(800, 11)

In [17]:
df.head()

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
0,2025-01-01,Brasília,DF,33.7,60.9,44.6,31.8,25.5,57.8,61.7,Moderado
1,2025-01-01,Curitiba,PR,25.7,22.1,29.4,40.0,17.1,77.4,43.4,Moderado
2,2025-01-01,Salvador,BA,18.8,27.6,29.2,60.2,29.3,78.0,47.5,Moderado
3,2025-01-02,Curitiba,PR,12.4,41.1,20.0,32.6,20.3,85.7,35.8,Bom
4,2025-01-03,Belo Horizonte,MG,32.0,57.3,36.4,23.5,26.3,74.6,54.1,Moderado

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 800 non-null    str
 1   cidade               800 non-null    str
 2   estado               800 non-null    str
 3   pm25                 800 non-null    float64
 4   pm10                 800 non-null    float64
 5   no2                  800 non-null    float64
 6   o3                   800 non-null    float64
 7   temperatura          800 non-null    float64
 8   umidade              800 non-null    float64
 9   indice_qualidade_ar  800 non-null    float64
 10  nivel_alerta         800 non-null    str
dtypes: float64(7), str(4)
memory usage: 68.9 KB

In [19]:
df.describe()

,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,26.597625,46.84950,27.537125,32.405125,25.640500,74.918750,47.758375
std,8.983311,13.63357,9.157577,9.247010,4.608675,9.492972,8.747129
min,6.000000,12.20000,5.000000,8.000000,14.500000,47.300000,28.600000
25%,20.400000,37.10000,21.700000,25.400000,22.300000,69.275000,41.600000
50%,25.900000,46.30000,26.800000,32.500000,25.850000,76.250000,46.900000
75%,32.000000,55.10000,32.900000,38.400000,29.100000,81.425000,53.500000
max,60.100000,91.60000,61.700000,68.100000,36.100000,96.000000,86.300000

In [20]:
df.isnull().sum()

data                   0
cidade                 0
estado                 0
pm25                   0
pm10                   0
no2                    0
o3                     0
temperatura            0
umidade                0
indice_qualidade_ar    0
nivel_alerta           0
dtype: int64

## Perguntas

1. Quantas medições existem no dataset?

- R: indices de pm25, pm10, no2, o3, temperatura, umidade, indice de qualidade do ar e nivel de alerta

2. Quantas cidades estão presentes na base?

- R: 10

3. Quais colunas representam poluentes atmosféricos?

- R: PM25, PM10, NO2 e O3

4. Existem valores ausentes no dataset?

- R: 0 valores

# Parte 3 - Análise por cidade

In [55]:
df['cidade'].unique()

<StringArray>
[      'Brasília',       'Curitiba',       'Salvador', 'Belo Horizonte',
         'Recife',      'Fortaleza', 'Rio de Janeiro',   'Porto Alegre',
         'Manaus',      'São Paulo']
Length: 10, dtype: str

In [ ]:
df.groupby('cidade')[['pm25', 'pm10', 'no2', 'o3']].mean()

# Parte 4 - Análise do índice de qualidade do ar

In [39]:
df.groupby('cidade')[['pm25', 'pm10', 'no2', 'o3',]].mean().sort_values(by=['pm25', 'pm10', 'no2', 'o3'], ascending=False)

                     pm25       pm10        no2         o3
cidade
São Paulo       33.653125  56.256250  39.314062  34.878125
Brasília        31.351724  59.428736  29.926437  33.167816
Belo Horizonte  27.874026  48.409091  27.992208  30.141558
Rio de Janeiro  27.825301  43.106024  30.925301  38.836145
Porto Alegre    26.798592  47.760563  27.959155  27.991549
Manaus          26.271084  46.898795  22.566265  30.354217
Curitiba        25.339785  43.408602  26.151613  28.435484
Recife          23.416471  41.165882  24.320000  32.205882
Fortaleza       23.186250  44.662500  24.232500  34.176250
Salvador        21.503896  39.102597  24.568831  34.274026

## Perguntas

1. Qual cidade apresenta pior qualidade média do ar?

- R: São Paulo

2. Qual cidade apresenta melhor qualidade do ar?

- R: Salvador

# Parte 5 - Filtragem por nível de alerta

In [53]:
df_alerta = df[df['nivel_alerta'].isin(['Ruim', 'Muito RUim'])]
df_alerta.count().unique()

array([14])

In [47]:
df['cidade'].value_counts().sort_values(ascending=False)

cidade
Curitiba          93
Brasília          87
Recife            85
Rio de Janeiro    83
Manaus            83
Fortaleza         80
Salvador          77
Belo Horizonte    77
Porto Alegre      71
São Paulo         64
Name: count, dtype: int64

## Perguntas

1. Quantos registros possuem alerta crítico?

- R: 14

2. Em quais cidades eles ocorrem com maior frequência?

- R: Curitiba, Brasília e Recife

# Parte 6 - Ranking dos dias mais críticos

In [54]:
df.sort_values('indice_qualidade_ar', ascending=False).head(10)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim

## Perguntas

1. Qual o pior dia registrado?

- R:2025-08-19

2. Em qual cidade ocorreu?

- R:São Paulo

3. Quais poluentes estavam mais altos nesse dia?

- R: PM10 e PM25

# Parte 7 - Análise temporal